[versions]
codion = "0.18.67"
logback = "1.5.27"
commons = "1.28.0"
jna = "5.18.1"

[libraries]
codion-common-bom = { module = "is.codion:codion-common-bom", version.ref = "codion" }

codion-swing-common-ui = { module = "is.codion:codion-swing-common-ui" }
codion-plugin-flatlaf-themes = { group = "is.codion", name = "codion-plugin-flatlaf-themes" }
codion-plugin-flatlaf-intellij-themes = { module = "is.codion:codion-plugin-flatlaf-intellij-themes" }
codion-plugin-logback = { module = "is.codion:codion-plugin-logback-proxy" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }